DROP TABLE IF EXISTS bike;
DROP TABLE IF EXISTS wheels;
DROP TABLE IF EXISTS handlebars;
DROP TABLE IF EXISTS frame_set;
DROP TABLE IF EXISTS staff;
DROP TABLE IF EXISTS addresses;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS orders;